[versions]
kotlin = "2.3.0"
kotlinter = "5.3.0"
kermit = "2.0.8"
central = "2.0.2"
dokka = "2.1.0"
coroutines = "1.10.2"

[libraries]
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
central = { id = "cn.lalaki.central", version.ref = "central"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
